### ISSUE TITLE
Shouldn't OSG support be removed?

### ISSUE THREAD

**Issue by gwarf** [EGI-Foundation/glite-info-update-endpoints#11]
As discussed on [GGUS](https://ggus.eu/index.php?mode=ticket_info&ticket_id=132611#update#15) it seems that OSG decommissioned their BDII support and now tob-levels BDIIs should not have any OSG mention.
This need to be clarified, and in the meantime it's possible to disable OSG in the configuration file: https://github.com/EGI-Foundation/glite-info-update-endpoints/blob/314ac0f1d71b0e7d599691bdb000fb69db7f2c1e/etc/glite-info-update-endpoints.conf#L3

**Comment by maarten-litmaath** [comment]
OK, thanks!
